In [1]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
import json

In [2]:
prev_years = pd.read_csv('metsa_ja_maastikutulekahjud_2014_kuni_2020.csv',index_col=0,delimiter="\t")
current_year = pd.read_csv('metsa_ja_maastikutulekahjud_jooksev_aasta.csv',index_col=0,delimiter="\t")

In [3]:
prev_years.columns

Index(['sundmuse_kuupaev_dt', 'tulekahju_liik', 'sundmuse_alamliik',
       'mis_poles', 'wgs_latitude', 'wgs_longitude', 'maakond', 'kov',
       'korgem_aste', 'hairekeskuses_registreerimine', 'esimene_alarmeerimine',
       'esimene_valjasoit', 'esimese_kohalejoudnud_aeg', 'lokaliseerimise_aeg',
       'likvideerimise_aeg', 'viimase_ressursi_lahkumise_aeg',
       'sundmuse_kestvus', 'valjasoidu_korralduste_arv',
       'valjasoitnud_ressursside_arv', 'annulleeritud_ressursside_arv',
       'kohal_ressursside_arv'],
      dtype='object')

In [4]:
current_year.head(10)

,sundmuse_kuupaev_dt,tulekahju_liik,sundmuse_alamliik,mis_poles,wgs_latitude,wgs_longitude,maakond,kov,korgem_aste,hairekeskuses_registreerimine,...,esimene_valjasoit,esimese_kohalejoudnud_aeg,lokaliseerimise_aeg,likvideerimise_aeg,viimase_ressursi_lahkumise_aeg,sundmuse_kestvus,valjasoidu_korralduste_arv,valjasoitnud_ressursside_arv,annulleeritud_ressursside_arv,kohal_ressursside_arv
sundmuse_number,,,,,,,,,,,,,,,,,,,,,
2111040267,2021-11-04,Metsa-ja maastikutulekahju,NaN,NaN,57.840,26.059,Valga maakond,Valga vald,PÄÄSTE 1,2021-11-04 09:26:12,...,2021-11-04 09:27:27,2021-11-04 09:35:18,NaN,NaN,2021-11-04 09:39:42,00:13:30,NaN,1.0,NaN,1.0
2111020338,2021-11-02,Metsa-ja maastikutulekahju,NaN,NaN,59.304,24.678,Harju maakond,Saku vald,PÄÄSTE 2,2021-11-02 10:34:38,...,2021-11-02 10:35:44,2021-11-02 10:47:15,NaN,2021-11-02 11:02:34,2021-11-02 11:03:59,00:29:21,NaN,4.0,NaN,2.0
2110310649,2021-10-31,Metsa-ja maastikutulekahju,NaN,NaN,59.562,24.820,Harju maakond,Viimsi vald,PÄÄSTE 2,2021-10-31 12:02:21,...,2021-10-31 12:03:33,2021-10-31 12:26:10,NaN,2021-10-31 12:42:01,2021-10-31 12:56:53,00:54:32,NaN,3.0,NaN,3.0
2110301423,2021-10-30,Metsa-ja maastikutulekahju,NaN,NaN,58.561,26.633,Tartu maakond,Tartu vald,PÄÄSTE 2,2021-10-30 21:30:59,...,2021-10-30 21:32:09,2021-10-30 21:41:00,NaN,2021-10-30 21:57:30,2021-10-30 22:00:01,00:29:02,NaN,5.0,NaN,3.0
2110220469,2021-10-22,Metsa-ja maastikutulekahju,NaN,NaN,58.662,25.609,Järva maakond,Türi vald,PÄÄSTE 1,2021-10-22 08:43:53,...,2021-10-22 08:48:06,2021-10-22 09:04:09,NaN,NaN,2021-10-22 09:22:26,00:38:33,NaN,1.0,NaN,1.0
2110190525,2021-10-19,Metsa-ja maastikutulekahju,NaN,NaN,59.419,28.103,Ida-Viru maakond,Narva-Jõesuu linn,PÄÄSTE 1,2021-10-19 12:37:48,...,2021-10-19 12:38:37,2021-10-19 12:55:11,NaN,NaN,2021-10-19 13:17:59,00:40:11,NaN,1.0,NaN,1.0
2110181028,2021-10-18,Metsa-ja maastikutulekahju,NaN,NaN,58.900,25.570,Järva maakond,Paide linn,PÄÄSTE 2,2021-10-18 17:34:43,...,2021-10-18 17:37:04,2021-10-18 17:51:39,NaN,NaN,2021-10-18 18:42:25,01:07:42,NaN,10.0,NaN,9.0
2110121249,2021-10-12,Metsa-ja maastikutulekahju,NaN,NaN,58.894,26.029,Järva maakond,Järva vald,PÄÄSTE 1,2021-10-12 20:53:27,...,2021-10-12 21:23:26,2021-10-12 21:35:34,NaN,2021-10-12 21:52:18,2021-10-12 22:28:16,01:34:49,NaN,1.0,NaN,1.0
2110111178,2021-10-11,Metsa-ja maastikutulekahju,NaN,NaN,59.460,24.893,Harju maakond,Tallinn,PÄÄSTE 1,2021-10-11 18:06:04,...,2021-10-11 18:07:01,2021-10-11 18:14:59,NaN,NaN,2021-10-11 19:04:38,00:58:34,NaN,1.0,NaN,1.0
2110091096,2021-10-09,Metsa-ja maastikutulekahju,NaN,NaN,58.025,27.115,Põlva maakond,Põlva vald,PÄÄSTE 2,2021-10-09 16:42:50,...,2021-10-09 16:44:35,2021-10-09 16:58:01,NaN,NaN,2021-10-09 17:08:57,00:26:07,NaN,6.0,NaN,4.0

In [5]:
prev_years.describe()

,wgs_latitude,wgs_longitude,valjasoidu_korralduste_arv,valjasoitnud_ressursside_arv,annulleeritud_ressursside_arv,kohal_ressursside_arv
count,8648.000000,8648.000000,8647.000000,8624.000000,2693.000000,8585.000000
mean,59.027432,25.870395,3.206777,2.936109,2.687709,2.355154
std,0.521018,1.418205,5.080207,4.443308,1.975741,4.049440
min,57.542000,21.855000,1.000000,1.000000,1.000000,1.000000
25%,58.625000,24.730000,1.000000,1.000000,1.000000,1.000000
50%,59.334000,25.779500,2.000000,1.000000,2.000000,1.000000
75%,59.402000,27.237000,4.000000,4.000000,4.000000,2.000000
max,59.637000,28.205000,179.000000,164.000000,29.000000,158.000000

In [6]:
current_year.describe()

,wgs_latitude,wgs_longitude,valjasoidu_korralduste_arv,valjasoitnud_ressursside_arv,annulleeritud_ressursside_arv,kohal_ressursside_arv
count,810.000000,810.000000,491.000000,809.000000,181.000000,805.000000
mean,58.929505,25.811815,3.482688,4.789864,2.823204,3.634783
std,0.535248,1.358704,3.133298,7.093983,1.804843,6.338172
min,57.610000,22.028000,1.000000,1.000000,1.000000,1.000000
25%,58.467250,24.701000,1.000000,1.000000,1.000000,1.000000
50%,59.185500,25.725500,2.000000,3.000000,2.000000,2.000000
75%,59.389000,26.994000,5.000000,6.000000,4.000000,4.000000
max,59.647000,28.196000,24.000000,90.000000,9.000000,85.000000

In [7]:
import datetime
data = pd.concat([prev_years, current_year], ignore_index = True)

#String to DateTime
data['sundmuse_kuupaev_dt'] = pd.to_datetime(data['sundmuse_kuupaev_dt'])
data['hairekeskuses_registreerimine'] = pd.to_datetime(data['hairekeskuses_registreerimine'])
data['sundmuse_kuupaev_dt'] = pd.to_datetime(data['sundmuse_kuupaev_dt'])
data['hairekeskuses_registreerimine'] = pd.to_datetime(data['hairekeskuses_registreerimine'])
data['esimene_alarmeerimine'] = pd.to_datetime(data['esimene_alarmeerimine'])
data['esimene_valjasoit'] = pd.to_datetime(data['esimene_valjasoit'])
data['esimese_kohalejoudnud_aeg'] = pd.to_datetime(data['esimese_kohalejoudnud_aeg'])
data['lokaliseerimise_aeg'] = pd.to_datetime(data['lokaliseerimise_aeg'])
data['likvideerimise_aeg'] = pd.to_datetime(data['likvideerimise_aeg'])
data['viimase_ressursi_lahkumise_aeg'] = pd.to_datetime(data['viimase_ressursi_lahkumise_aeg'])
data['sundmuse_kestvus'] = data['sundmuse_kestvus'].astype(str)


#String to Numeric
data['wgs_latitude'] = pd.to_numeric(data['wgs_latitude'])
data['wgs_longitude'] = pd.to_numeric(data['wgs_longitude'])
data['valjasoidu_korralduste_arv'] = pd.to_numeric(data['valjasoidu_korralduste_arv'])
data['valjasoitnud_ressursside_arv'] = pd.to_numeric(data['valjasoitnud_ressursside_arv'])
data['annulleeritud_ressursside_arv'] = pd.to_numeric(data['annulleeritud_ressursside_arv'])
data['kohal_ressursside_arv'] = pd.to_numeric(data['kohal_ressursside_arv'])

data.dtypes

sundmuse_kuupaev_dt               datetime64[ns]
tulekahju_liik                            object
sundmuse_alamliik                         object
mis_poles                                 object
wgs_latitude                             float64
wgs_longitude                            float64
maakond                                   object
kov                                       object
korgem_aste                               object
hairekeskuses_registreerimine     datetime64[ns]
esimene_alarmeerimine             datetime64[ns]
esimene_valjasoit                 datetime64[ns]
esimese_kohalejoudnud_aeg         datetime64[ns]
lokaliseerimise_aeg               datetime64[ns]
likvideerimise_aeg                datetime64[ns]
viimase_ressursi_lahkumise_aeg    datetime64[ns]
sundmuse_kestvus                          object
valjasoidu_korralduste_arv               float64
valjasoitnud_ressursside_arv             float64
annulleeritud_ressursside_arv            float64
kohal_ressursside_arv                    float64
dtype: object

In [8]:
def dt64_to_float(dt64):
     year = dt64.astype('M8[Y]')
     days = (dt64 - year).astype('timedelta64[D]')
     year_next = year + np.timedelta64(1, 'Y')
     days_of_year = (year_next.astype('M8[D]') - year.astype('M8[D]')).astype('timedelta64[D]')
     dt_float = 1970 + year.astype(float) + days / (days_of_year)
     return dt_float
df1 = data.copy()
df1['hairekeskuses_registreerimine'] = dt64_to_float(df1['hairekeskuses_registreerimine'].to_numpy())
df1['esimene_alarmeerimine'] = dt64_to_float(df1['esimene_alarmeerimine'].to_numpy())
df1['esimene_valjasoit'] = dt64_to_float(df1['esimene_valjasoit'].to_numpy())
df1['esimese_kohalejoudnud_aeg'] = dt64_to_float(df1['esimese_kohalejoudnud_aeg'].to_numpy())
df1['lokaliseerimise_aeg'] = dt64_to_float(df1['lokaliseerimise_aeg'].to_numpy())
df1['likvideerimise_aeg'] = dt64_to_float(df1['likvideerimise_aeg'].to_numpy())
df1['viimase_ressursi_lahkumise_aeg'] = dt64_to_float(df1['viimase_ressursi_lahkumise_aeg'].to_numpy())
df1['sundmuse_kuupaev_dt'] = dt64_to_float(df1['sundmuse_kuupaev_dt'].to_numpy())

In [31]:
#df = data.copy()
df = df1.copy()
df.drop(df.loc[df['sundmuse_kestvus']=='nan'].index, inplace=True)
df = df.drop('viimase_ressursi_lahkumise_aeg', 1)
df = df.drop('lokaliseerimise_aeg', 1)
df = df.drop('likvideerimise_aeg', 1)

kestvused = df['sundmuse_kestvus'].to_numpy()

for x in range(len(kestvused)):
    kestvus = kestvused[x].split(":")
    tunnid = int(kestvus[0])
    minutid = int(kestvus[1])
    sekundid = int(kestvus[2])
    
    kokku = tunnid + minutid/60 + sekundid/3600
    
    kestvused[x] = kokku
    
df['sundmuse_kestvus'] = kestvused.tolist()
#df[df.select_dtypes(np.float64).columns] = df.select_dtypes(np.float64).astype(np.float32)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9433 entries, 0 to 9457
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   sundmuse_kuupaev_dt            9433 non-null   float64
 1   tulekahju_liik                 9433 non-null   object
 2   sundmuse_alamliik              9114 non-null   object
 3   mis_poles                      8216 non-null   object
 4   wgs_latitude                   9433 non-null   float64
 5   wgs_longitude                  9433 non-null   float64
 6   maakond                        9433 non-null   object
 7   kov                            9433 non-null   object
 8   korgem_aste                    9433 non-null   object
 9   hairekeskuses_registreerimine  9433 non-null   float64
 10  esimene_alarmeerimine          3135 non-null   float64
 11  esimene_valjasoit              9433 non-null   float64
 12  esimese_kohalejoudnud_aeg      9390 non-null   float64
 13  sundmuse_kestvus               9433 non-null   float64
 14  valjasoidu_korralduste_arv     9114 non-null   float64
 15  valjasoitnud_ressursside_arv   9433 non-null   float64
 16  annulleeritud_ressursside_arv  2851 non-null   float64
 17  kohal_ressursside_arv          9390 non-null   float64
dtypes: float64(12), object(6)
memory usage: 1.4+ MB

In [32]:
data_dum = pd.get_dummies(df, columns=['tulekahju_liik', 'sundmuse_alamliik', 'mis_poles', 'maakond', 'kov', 'korgem_aste'])
data_dum.fillna(data_dum.mean(), inplace=True)

In [33]:
y = data_dum['sundmuse_kestvus']
X = data_dum.loc[:, data_dum.columns != 'sundmuse_kestvus']

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [35]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score
import sklearn.metrics as sm

# Create linear regression object
regr = linear_model.LinearRegression()


# Train the model using the training sets
regr.fit(X_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(X_test)

print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2))

# The coefficients
#print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

Explain variance score = -6.962132825437297e+17
Mean squared error: 106940871232083705856.00
Coefficient of determination: -696328222254441600.00

In [36]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X_train, y_train)
y_preds = neigh.predict(X_test)

print("Coefficient of determination: %.2f" % r2_score(y_test, y_preds))

Coefficient of determination: 0.43

In [44]:
from sklearn.linear_model import Ridge
#Fit the model
ridgereg = Ridge(alpha=1.0,normalize=True)
ridgereg.fit(X_train, y_train)
y_pred = ridgereg.predict(X_test)
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2))

Coefficient of determination: 0.47
Mean squared error: 81.69
Explain variance score = 0.47

In [45]:
from sklearn.linear_model import Lasso
#Fit the model
lassoreg = Lasso(alpha=1.0)
lassoreg.fit(X_train, y_train)
y_pred = lassoreg.predict(X_test)
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2))

Coefficient of determination: 0.49
Mean squared error: 78.82
Explain variance score = 0.49

In [55]:
from sklearn.linear_model import ElasticNet
regr = ElasticNet(random_state=0)
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2))

Coefficient of determination: 0.49
Mean squared error: 78.47
Explain variance score = 0.49